In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [2]:
df = pd.read_csv('train.csv', index_col=0)
df.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied


In [3]:
X = df.drop(['id', 'Customer Type', 'Gender', 'satisfaction'], axis=1)
y= df['satisfaction']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
model = CatBoostClassifier(verbose=False)
model.fit(X_train, y_train, cat_features= ['Type of Travel', 'Class'])
y_pred = model.predict(X_test)

In [7]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, pos_label='satisfied'))
print(recall_score(y_test, y_pred, pos_label='satisfied'))
print(f1_score(y_test, y_pred, pos_label='satisfied'))

                         precision    recall  f1-score   support

neutral or dissatisfied       0.95      0.97      0.96     11713
              satisfied       0.97      0.94      0.95      9068

               accuracy                           0.96     20781
              macro avg       0.96      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

[[11417   296]
 [  545  8523]]
0.9595303402146191
0.9664361038666516
0.9398985443317159
0.9529826130709453


In [16]:
# с Departure/Arrival time convenient
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

                         precision    recall  f1-score   support

neutral or dissatisfied       0.95      0.97      0.96     11713
              satisfied       0.97      0.94      0.95      9068

               accuracy                           0.96     20781
              macro avg       0.96      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

[[11417   296]
 [  545  8523]]
0.9595303402146191


In [21]:
# с Departure/Arrival time convenient и Gender
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

                         precision    recall  f1-score   support

neutral or dissatisfied       0.95      0.97      0.96     11713
              satisfied       0.97      0.94      0.95      9068

               accuracy                           0.96     20781
              macro avg       0.96      0.96      0.96     20781
           weighted avg       0.96      0.96      0.96     20781

[[11412   301]
 [  544  8524]]
0.9593378566960205
